# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id_appointment', models.IntegerField(primary_key=True, serialize=False)),
                ('schedule', models.DateField()),
                ('observations', models.TextField()),
                ('service', models.CharField(max_length=45)),
                ('clinic', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id_comments', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id_field', models.IntegerField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=250)),
                ('field_number', models.IntegerField()),
                ('field_type', models.IntegerField()),
                ('field_tag', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id_form', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormHasField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('int_answer', models.IntegerField(blank=True, null=True)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('bool_answer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_has_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormHasFormTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwser_col_1', models.CharField(blank=True, max_length=45, null=True)),
                ('answer_col_2', models.CharField(blank=True, max_length=45, null=True)),
                ('answer_col_3', models.CharField(blank=True, max_length=45, null=True)),
                ('answer_col_4', models.CharField(blank=True, max_length=45, null=True)),
                ('answer_col_5', models.CharField(blank=True, max_length=45, null=True)),
                ('answer_col_6', models.CharField(blank=True, max_length=45, null=True)),
                ('answer_col_7', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'form_has_form_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormTable',
            fields=[
                ('id_form_table', models.IntegerField(primary_key=True, serialize=False)),
                ('column_number', models.IntegerField()),
                ('table_name', models.CharField(max_length=50)),
                ('column1', models.CharField(blank=True, max_length=45, null=True)),
                ('column2', models.CharField(blank=True, max_length=45, null=True)),
                ('column3', models.CharField(blank=True, max_length=45, null=True)),
                ('column4', models.CharField(blank=True, max_length=45, null=True)),
                ('column5', models.CharField(blank=True, max_length=45, null=True)),
                ('column6', models.CharField(blank=True, max_length=45, null=True)),
                ('column7', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'form_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id_form_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'form_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id_record', models.IntegerField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(blank=True, max_length=45, null=True)),
                ('record_date', models.DateField()),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestDemograficResult',
            fields=[
                ('id_test_demografic_result', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('relationship', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'test_demografic_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestOrganizationGeneralForm',
            fields=[
                ('id_test_organization_general_form', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('marital_status', models.CharField(max_length=45)),
                ('education', models.CharField(max_length=45)),
                ('job', models.CharField(max_length=45)),
                ('working_time', models.CharField(max_length=45)),
                ('organization_size', models.CharField(max_length=45)),
                ('organization_tipe', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'test_organization_general_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id_test_questions', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('max_val', models.IntegerField()),
            ],
            options={
                'db_table': 'test_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id_test_result', models.IntegerField(primary_key=True, serialize=False)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('generated_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'test_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserEducationExperience',
            fields=[
                ('id_user_education_experience', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=150)),
                ('first_date', models.TextField()),
                ('last_date', models.TextField()),
                ('education_type', models.IntegerField()),
            ],
            options={
                'db_table': 'user_education_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserHasTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_has_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id_user_skills', models.IntegerField(primary_key=True, serialize=False)),
                ('computer_skill', models.IntegerField()),
                ('learning_skill', models.IntegerField()),
                ('ethic_skill', models.IntegerField()),
                ('responsability_skill', models.IntegerField()),
                ('strategy_skill', models.IntegerField()),
                ('professional_growth_skill', models.IntegerField()),
                ('professional_relationships_skill', models.IntegerField()),
                ('interpersonal_relationships_skill', models.IntegerField()),
                ('knowledge_skill', models.IntegerField()),
                ('problem_solver_skill', models.IntegerField()),
                ('effective_communication_skill', models.IntegerField()),
                ('control_skill', models.IntegerField()),
                ('adaptability_skill', models.IntegerField()),
                ('creativity_skill', models.IntegerField()),
                ('decision_making_skill', models.IntegerField()),
                ('emotional_skill', models.IntegerField()),
                ('opportunity_identification_skill', models.IntegerField()),
                ('team_work_skill', models.IntegerField()),
                ('lidership_skill', models.IntegerField()),
                ('conflict_manage_skill', models.IntegerField()),
                ('proactivity', models.IntegerField()),
                ('user_skillscol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserWorkExperience',
            fields=[
                ('id_user_experience', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=150)),
                ('job_position', models.CharField(max_length=150)),
                ('first_date', models.TextField()),
                ('last_date', models.TextField()),
            ],
            options={
                'db_table': 'user_work_experience',
                'managed': False,
            },
        ),
    ]
