# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedarea', '0002_appointment_client_comments_field_form_formhasfield_formhasformtable_formtable_formtype_record_test_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Induction',
            fields=[
                ('id_induction', models.IntegerField(primary_key=True, serialize=False)),
                ('module_1', models.IntegerField()),
                ('module_2', models.IntegerField()),
                ('module_3', models.IntegerField()),
                ('module_4', models.IntegerField()),
            ],
            options={
                'db_table': 'induction',
                'managed': False,
            },
        ),
    ]
