# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedarea', '0004_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id_upload_form', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upload_form',
                'managed': False,
            },
        ),
    ]
