# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id_field', models.IntegerField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=250)),
                ('field_number', models.IntegerField()),
                ('field_type', models.IntegerField()),
                ('field_tag', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id_form_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'form_type',
                'managed': False,
            },
        ),
    ]
